# -*- coding: utf-8 -*-
"""Folium.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18RxkjpTb8dyFrUI8DNlQFJe4_P3eb0g8

# Folium
"""

#!pip list

#!pip install folium --upgrade

import folium

# Cria um mapa centrado em SP
#mapa = folium.Map(location=[-23.989405563151248, -46.40751287046697], zoom_start=12)
mapa = folium.Map(location=[-23.989405563151248, -46.40751287046697], zoom_start=12)

# adicionar um marcador para a Fatec PG
folium.Marker(location=[-24.004904557888242, -46.41226830599094], popup='Fatec PG', icon=folium.Icon(color='red')).add_to(mapa)

folium.Marker(location=[-24.0059458994018, -46.413400391480984], popup='Smart Fit PG', icon=folium.Icon(color='blue')).add_to(mapa)

folium.Marker(location=[-23.96879506296125, -46.384774881636154], popup='Centro SV', icon=folium.Icon(color='green')).add_to(mapa)

folium.Marker(location=[-23.965612789101225, -46.31605670420712], popup='médico Embaré', icon=folium.Icon(color='purple')).add_to(mapa)

mapa.save("mapa.html")